---
galaxy_info:
  author: elnappo <elnappo@nerdpol.io>
  description: Install quassel-core
  license: MIT
  min_ansible_version: 1.9
  platforms:
  - name: Ubuntu
    versions:
    - precise
    - trusty
  - name: Debian
    versions:
    - wheezy
    - jessie
  categories:
  - networking
  - chat

dependencies: []
