---
sudo: required
env:
  #matrix:
  - OS_TYPE=centos OS_VERSION=7 ANSIBLE_VERSION=1.9.2

before_install:
  - sudo yum install python-pip
install:
  - pip install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../' >ansible.cfg
  - echo localhost > inventory
script:
  - ansible-playbook -i inventory --syntax-check --list-tasks test.yml
  - ansible-playbook -i inventory --connection=local --become -vvvv test.yml
  - >
    ansible-playbook -i inventory --connection=local --become test.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
after_script:
  - quasselcore --version
  - cat /etc/default/quasselcore
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
