---
# tasks file for ansible-role-quassel-core
- name: Install epel packages
  yum: name=epel-release state=latest

- name: Install quassel-core
  yum: name=quassel-core state=latest

- name: Install postgresql-server
  yum: name=postgresql-server state=latest

- name: Install qt-postgresql
  yum: name=qt-postgresql state=latest

- name: Set quassel-core port
  lineinfile: dest=/etc/default/quasselcore regexp='^PORT' line='PORT="{{ quasselcore_port }}"' owner=root group=root mode=0644
  notify:
  - restart quassel-core

- name: Enable quassel-core on boot
  service: name=quasselcore state=started enabled=yes

- name: Setup ufw firewall rule
  ufw: rule=allow port={{ quasselcore_port }} proto=tcp
  when: quasselcore_setup_ufw
